version: "3.8"

services:
  postgres:
    container_name: postgress_db
    image: postgis/postgis:13-3.3-alpine 
    environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: test
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./pg_admin:/var/lib/pgadmin
      - ./backups:/backups
    ports:
      - "5050:80"
  redis:
    container_name: redis_container
    image: redis
    ports:
      - "6379:6379"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9201:9200"
      - "9300:9300"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2
    container_name: kibana-container
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
