version: "3.8"

services:
  postgres:
    container_name: postgress_db
    image: postgis/postgis:13-3.3-alpine 
    environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: test
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./pg_admin:/var/lib/pgadmin
      - ./backups:/backups
    ports:
      - "5050:80"